#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

WORKSPACE = Path('/Users/nova/.openclaw/workspace')
TOKEN = WORKSPACE / 'google-auth/token.json'
SCOPES = [
    'https://www.googleapis.com/auth/presentations',
    'https://www.googleapis.com/auth/drive.file',
]

SLIDE_W = 10_000_000
SLIDE_H = 5_625_000


def emu(v: int) -> dict:
    return {'magnitude': v, 'unit': 'EMU'}


def transform(x: int, y: int) -> dict:
    return {'scaleX': 1, 'scaleY': 1, 'translateX': x, 'translateY': y, 'unit': 'EMU'}


def rgb(hex_color: str) -> dict:
    h = hex_color.lstrip('#')
    return {'red': int(h[0:2], 16) / 255, 'green': int(h[2:4], 16) / 255, 'blue': int(h[4:6], 16) / 255}


def create_slide(reqs: list[dict], sid: str) -> None:
    reqs.append({'createSlide': {'objectId': sid, 'slideLayoutReference': {'predefinedLayout': 'BLANK'}}})
    reqs.append({
        'updatePageProperties': {
            'objectId': sid,
            'pageProperties': {'pageBackgroundFill': {'solidFill': {'color': {'rgbColor': rgb('#F7F8FB')}}}},
            'fields': 'pageBackgroundFill.solidFill.color',
        }
    })


def textbox(reqs: list[dict], sid: str, oid: str, text: str, x: int, y: int, w: int, h: int,
            font_size: int = 16, bold: bool = False, color: str = '#1F2937', bg: str | None = None) -> None:
    reqs.append({
        'createShape': {
            'objectId': oid,
            'shapeType': 'TEXT_BOX',
            'elementProperties': {
                'pageObjectId': sid,
                'size': {'width': emu(w), 'height': emu(h)},
                'transform': transform(x, y),
            },
        }
    })
    if bg:
        reqs.append({
            'updateShapeProperties': {
                'objectId': oid,
                'shapeProperties': {'shapeBackgroundFill': {'solidFill': {'color': {'rgbColor': rgb(bg)}}}},
                'fields': 'shapeBackgroundFill.solidFill.color',
            }
        })
    reqs.append({'insertText': {'objectId': oid, 'text': text}})
    reqs.append({
        'updateTextStyle': {
            'objectId': oid,
            'textRange': {'type': 'ALL'},
            'style': {
                'fontSize': {'magnitude': font_size, 'unit': 'PT'},
                'foregroundColor': {'opaqueColor': {'rgbColor': rgb(color)}},
                'bold': bold,
                'fontFamily': 'Arial',
            },
            'fields': 'fontSize,foregroundColor,bold,fontFamily',
        }
    })


def title(reqs: list[dict], sid: str, n: int, main: str, sub: str = '') -> None:
    textbox(reqs, sid, f'{sid}_title', main, 500_000, 330_000, 8_900_000, 470_000, 26, True, '#111827')
    if sub:
        textbox(reqs, sid, f'{sid}_sub', sub, 510_000, 800_000, 8_800_000, 270_000, 11, False, '#6B7280')
    textbox(reqs, sid, f'{sid}_page', f'{n:02d}', 9_100_000, 5_050_000, 400_000, 200_000, 9, False, '#9CA3AF')


def main() -> None:
    creds = Credentials.from_authorized_user_file(str(TOKEN), SCOPES)
    slides = build('slides', 'v1', credentials=creds)
    drive = build('drive', 'v3', credentials=creds)

    deck = slides.presentations().create(body={'title': 'SupportDev Monthly Report Placeholder Template'}).execute()
    pid = deck['presentationId']
    default_sid = deck['slides'][0]['objectId']

    reqs: list[dict] = [{'deleteObject': {'objectId': default_sid}}]
    sids = [f'support_tpl_{i}' for i in range(1, 8)]
    for sid in sids:
        create_slide(reqs, sid)

    # 1 Cover
    title(reqs, sids[0], 1, '{{TITLE}}', 'Reusable Google Slides template for SupportDev reporting')
    textbox(reqs, sids[0], 'cover_period', 'Period: {{REPORT_PERIOD}}  |  Weeks: {{WEEKS}}', 650_000, 1_450_000, 8_700_000, 350_000, 18, True, '#2563EB')
    textbox(reqs, sids[0], 'cover_summary', '{{EXECUTIVE_SUMMARY}}', 800_000, 2_150_000, 8_000_000, 900_000, 20, False, '#111827', '#FFFFFF')
    textbox(reqs, sids[0], 'cover_meta', 'Generated by Nova / OpenClaw + n8n automation glue', 800_000, 4_600_000, 7_000_000, 250_000, 10, False, '#6B7280')

    # 2 KPI overview
    title(reqs, sids[1], 2, 'Executive KPI Overview', '{{REPORT_PERIOD}}')
    metrics = [
        ('Total Tickets', '{{TOTAL_TICKETS}}'), ('AMAZE', '{{AMAZE_TICKETS}}'), ('Phoenix', '{{PHOENIX_TICKETS}}'), ('KD', '{{KD_TICKETS}}'),
        ('Resolved', '{{RESOLVED_TICKETS}}'), ('ggChat', '{{GGCHAT_TICKETS}}'), ('Avg SLA', '{{AVG_SLA}}'), ('Missed SLA', '{{MISSED_SLA}}'),
    ]
    x0, y0 = 650_000, 1_250_000
    for i, (label, ph) in enumerate(metrics):
        x = x0 + (i % 4) * 2_250_000
        y = y0 + (i // 4) * 1_350_000
        textbox(reqs, sids[1], f'kpi_{i}_label', label, x, y, 1_950_000, 250_000, 11, False, '#6B7280', '#FFFFFF')
        textbox(reqs, sids[1], f'kpi_{i}_val', ph, x, y + 300_000, 1_950_000, 500_000, 28, True, '#111827', '#FFFFFF')
    textbox(reqs, sids[1], 'kpi_summary', '{{KEY_METRICS_SUMMARY}}', 800_000, 4_050_000, 8_400_000, 700_000, 15, False, '#111827', '#FFFFFF')

    # 3 First response
    title(reqs, sids[2], 3, 'First Response Discipline', 'Primary operational risk')
    textbox(reqs, sids[2], 'fr_avg', 'Avg First Response\n{{AVG_FIRST_RESPONSE}}', 750_000, 1_300_000, 3_800_000, 1_000_000, 26, True, '#111827', '#DBEAFE')
    textbox(reqs, sids[2], 'fr_missed', 'Missed First Response\n{{MISSED_FIRST_RESPONSE}}', 5_050_000, 1_300_000, 3_800_000, 1_000_000, 26, True, '#991B1B', '#FEE2E2')
    textbox(reqs, sids[2], 'fr_actions', '{{FIRST_RESPONSE_ACTIONS}}', 900_000, 2_750_000, 8_200_000, 1_650_000, 16, False, '#111827', '#FFFFFF')

    # 4 SLA and resolution
    title(reqs, sids[3], 4, 'SLA / Resolution Health', 'Quality and recovery tracking')
    textbox(reqs, sids[3], 'sla_avg', 'Avg SLA\n{{AVG_SLA}}', 750_000, 1_250_000, 2_700_000, 900_000, 26, True, '#065F46', '#D1FAE5')
    textbox(reqs, sids[3], 'sla_missed', 'Missed SLA\n{{MISSED_SLA}}', 3_750_000, 1_250_000, 2_700_000, 900_000, 26, True, '#92400E', '#FEF3C7')
    textbox(reqs, sids[3], 'avg_resp', 'Avg Response\n{{AVG_RESPONSE_TIME}}', 6_750_000, 1_250_000, 2_300_000, 900_000, 22, True, '#111827', '#FFFFFF')
    textbox(reqs, sids[3], 'avg_res', 'Avg Resolution Time: {{AVG_RESOLUTION_TIME}}', 850_000, 2_650_000, 8_300_000, 450_000, 18, True, '#111827')
    textbox(reqs, sids[3], 'weekly_table', '{{WEEKLY_DATA_TABLE}}', 850_000, 3_200_000, 8_500_000, 1_450_000, 10, False, '#111827', '#FFFFFF')

    # 5 Issue insights
    title(reqs, sids[4], 5, 'Issue / Workload Insights', 'System mix, intake, and recurring risk')
    textbox(reqs, sids[4], 'issue_insights', '{{ISSUE_INSIGHTS}}', 850_000, 1_250_000, 8_500_000, 2_250_000, 17, False, '#111827', '#FFFFFF')
    textbox(reqs, sids[4], 'issue_note', 'Use this slide to call out workload shift, repeated themes, and ownership gaps before the next review.', 850_000, 4_000_000, 8_500_000, 500_000, 13, False, '#6B7280')

    # 6 Spike follow-up
    title(reqs, sids[5], 6, 'Spike Follow-up', 'Peak week and system-specific action')
    textbox(reqs, sids[5], 'peak_week', 'Peak Week\n{{PEAK_WEEK}}', 900_000, 1_300_000, 2_400_000, 900_000, 28, True, '#111827', '#E0E7FF')
    textbox(reqs, sids[5], 'peak_tickets', 'Peak Tickets\n{{PEAK_TICKETS}}', 3_800_000, 1_300_000, 2_400_000, 900_000, 28, True, '#111827', '#E0E7FF')
    textbox(reqs, sids[5], 'peak_phoenix', 'Peak Phoenix\n{{PEAK_PHOENIX}}', 6_700_000, 1_300_000, 2_400_000, 900_000, 28, True, '#111827', '#E0E7FF')
    textbox(reqs, sids[5], 'spike_follow', '{{SPIKE_FOLLOW_UP}}', 950_000, 2_750_000, 8_200_000, 1_700_000, 16, False, '#111827', '#FFFFFF')

    # 7 Next actions
    title(reqs, sids[6], 7, 'Recommended Next Actions', 'Lead-style follow-up board')
    textbox(reqs, sids[6], 'next_1', '1) First Response Guardrail\nOwner: Support Lead\nTrigger: missed FR > 5/day', 850_000, 1_250_000, 2_600_000, 1_350_000, 15, False, '#111827', '#FFFFFF')
    textbox(reqs, sids[6], 'next_2', '2) Phoenix Spike Mini-RCA\nOwner: App Support + Dev\nOutput: theme + prevention', 3_700_000, 1_250_000, 2_600_000, 1_350_000, 15, False, '#111827', '#FFFFFF')
    textbox(reqs, sids[6], 'next_3', '3) ggChat Intake Ownership\nOwner: Triage owner\nOutput: queue hygiene', 6_550_000, 1_250_000, 2_600_000, 1_350_000, 15, False, '#111827', '#FFFFFF')
    textbox(reqs, sids[6], 'next_summary', '{{EXECUTIVE_SUMMARY}}', 850_000, 3_250_000, 8_300_000, 900_000, 17, False, '#111827', '#F3F4F6')

    for i in range(0, len(reqs), 90):
        slides.presentations().batchUpdate(presentationId=pid, body={'requests': reqs[i:i + 90]}).execute()
    drive.permissions().create(fileId=pid, body={'type': 'anyone', 'role': 'reader'}, fields='id').execute()
    url = f'https://docs.google.com/presentation/d/{pid}/edit'
    out = WORKSPACE / 'google-slides-supportdev-placeholder-template-url.txt'
    out.write_text(url + '\n')
    print(url)


if __name__ == '__main__':
    main()
